application: athenasapp
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css))
  static_files: webapp/\1
  upload: webapp/(.*\.(gif|png|jpg|ico|js|css))

- url: /robots.txt
  static_files: webapp/robots.txt
  upload: webapp/robots.txt 

# re-direct to index.html if no path is give
- url: /
  static_files: webapp/index.html
  upload: webapp/index.html
  
libraries:       
- name: webapp2
  version: "2.5.1"                                                               
- name: jinja2                                                                  
  version: "2.6" 